### ISSUE TITLE
was this package deprecated?

### ISSUE THREAD

**Issue by avichyz** [vacuumlabs/validation#15]
How come it still isn't well documented?
how do I even run the example?
I'm used to npm, writing "npm run myRunCommand"

here it seems I should write npm run test
but it writes "no test specified" and some mre lines of errors

**Comment by marcelka** [comment]
To run the example:
1. Build the example:
`gulp build-example`
It creates the repository `public`, which includes all html and js needed to run the example.
2. Open the file `/path/to/validation-repo/public/index.html in your browser`. You do not need to run any server.

Let me know if you encounter any other issues.

As for the documentation, I postponed its polishing, because I came up with some improvements which I wanted to implement first. I expected to have these improvements done long time ago, but I was obviously wrong. I am planning to work on this library again in June (I do not have any time left before that). I hope to finish all the improvements, but I will at least make sure to add sufficient documentation.
